# Generated by Django 2.2.14 on 2020-09-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200928_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimages',
            name='fk_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
